kind: Service
apiVersion: v1
metadata:
  name: $APP-service
spec:
  type: NodePort
  selector:
    app: $APP
  ports:
  - protocol: TCP
    port: 30001
    nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $APP-deployment
  labels:
    app: $APP
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      containers:
      - name: $APP
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 30001
